import type { Metadata } from "next";
import LegalPage from "@/components/LegalPage";

export const metadata: Metadata = {
  title: "Opaque — Terms of Service",
  description: "Terms of Service for Opaque, the AI photo filter app by New Age Technologies Ltd.",
};

export default function Page() {
  return (
    <LegalPage title="Terms of Service" effectiveDate="July 28, 2026" backHref="/opaque" backLabel="Back to Opaque">
      <h2>1. Acceptance of Terms</h2>
      <p>
        By downloading or using Opaque (&quot;the App&quot;), operated by New Age Technologies Ltd.
        (&quot;we&quot;, &quot;us&quot;, &quot;our&quot;), registered at 40 Ossington Street, London W2
        4LY, United Kingdom, you agree to be bound by these Terms of Service. If you do not agree, do
        not use the App.
      </p>

      <h2>2. The Service</h2>
      <p>
        Opaque lets you transform photos using AI-powered filters and custom editing instructions.
        Edits are generated by third-party AI services (OpenAI and xAI). Results are
        computer-generated: they may be inaccurate, imperfect, or differ from what you expected, and
        the same request may produce different results each time.
      </p>

      <h2>3. Subscriptions and Purchases</h2>
      <ul>
        <li>
          <strong>Opaque Pro Yearly</strong> — billed annually, with a 3-day free trial for new
          subscribers. Payment is charged when the trial ends unless cancelled at least 24 hours
          before.
        </li>
        <li>
          <strong>Opaque Pro Weekly</strong> — billed weekly, no trial.
        </li>
        <li>
          <strong>Single edits</strong> — a one-time purchase that unlocks one AI generation.
        </li>
      </ul>
      <p>
        All payments are processed by Apple through your App Store account. Subscriptions renew
        automatically unless cancelled at least 24 hours before the end of the current period. You can
        manage or cancel your subscription at any time in your App Store account settings. Current
        prices are always shown in the App before purchase and may vary by region. Refunds are handled
        by Apple in accordance with App Store policies.
      </p>

      <h2>4. Acceptable Use</h2>
      <p>You agree not to use the App to:</p>
      <ul>
        <li>Edit or generate images that are unlawful, defamatory, or infringe the rights of others</li>
        <li>Process photos of people without their consent where consent is required</li>
        <li>Create misleading content intended to deceive, defraud, or impersonate</li>
        <li>Attempt to reverse-engineer, abuse, or disrupt the App or its AI services</li>
      </ul>

      <h2>5. Your Content</h2>
      <p>
        You retain all rights to the photos you submit and the edited results. You are responsible for
        ensuring you have the right to edit the photos you upload. By using the App you grant us the
        limited technical licence needed to transmit your photos to our AI providers for processing
        and to return the results to you.
      </p>

      <h2>6. Intellectual Property</h2>
      <p>
        The App, including its design, filters, prompts, and branding, is the property of New Age
        Technologies Ltd. and is protected by intellectual property laws. These Terms grant you a
        personal, non-exclusive, non-transferable licence to use the App on Apple devices you own or
        control.
      </p>

      <h2>7. AI-Generated Content Disclaimer</h2>
      <p>
        Edited images are produced by artificial intelligence. We make no warranty as to their
        accuracy, realism, or suitability for any purpose. You are responsible for how you use and
        share AI-edited images.
      </p>

      <h2>8. Limitation of Liability</h2>
      <p>To the maximum extent permitted by law:</p>
      <ul>
        <li>The App is provided &quot;as is&quot; without warranties of any kind</li>
        <li>We do not warrant that the App will be uninterrupted, error-free, or accurate</li>
        <li>We shall not be liable for any indirect, incidental, special, consequential, or punitive damages</li>
        <li>Our total liability shall not exceed the amount you paid for the App in the 12 months preceding the claim</li>
      </ul>

      <h2>9. Indemnification</h2>
      <p>
        You agree to indemnify and hold harmless New Age Technologies Ltd. from any claims, damages,
        or expenses arising from your use of the App or violation of these Terms.
      </p>

      <h2>10. Termination</h2>
      <p>
        We reserve the right to suspend or terminate your access to the App at any time, with or
        without cause, with or without notice. Upon termination, your right to use the App ceases
        immediately.
      </p>

      <h2>11. Governing Law</h2>
      <p>
        These Terms are governed by the laws of England and Wales. Any disputes shall be subject to
        the exclusive jurisdiction of the courts of England and Wales.
      </p>

      <h2>12. Changes to Terms</h2>
      <p>
        We may update these Terms from time to time. We will notify you of material changes by posting
        the updated Terms within the App or at this page. Your continued use of the App after changes
        constitutes acceptance.
      </p>

      <h2>13. Severability</h2>
      <p>
        If any provision of these Terms is found to be unenforceable, the remaining provisions shall
        continue in full force and effect.
      </p>

      <h2>14. Contact Us</h2>
      <p>If you have any questions about these Terms, please contact us at:</p>
      <p>
        New Age Technologies Ltd., 40 Ossington Street, London W2 4LY, United Kingdom
        <br />
        Email: <a href="mailto:fefeapphello@gmail.com">fefeapphello@gmail.com</a>
      </p>
    </LegalPage>
  );
}
